### ISSUE TITLE
Failing to save all libraries when `lib-libc-test` is detected on `kraft pkg update`

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#103]
This issue tracks fixing a bug which occurs during `kraft pkg update` which results in a whole manifest source entry being lost.  The was discovered with the following sequence:

```shell
kraft pkg source https://github.com/unikraft/lib-*
kraft pkg update
```

The source does not save if the library `lib-libc-test` appears in the list and instead silently fails.

To remedy this, this issue tracks, which must be completed in order:

 - [ ] Providing the ability to toggle between a "hard" and "soft" fail when performing the update.  A hard failure acts as it does now and must return the error in a visible fashion.  A soft failure will continue to update despite failures;
 - [ ] To determine why the name `lib-libc-test` name failed -- perhaps it is a regular expression error.

**Comment by craciunoiuc** [comment]
@nderjung shall we? 👀

**Comment by nderjung** [comment]
Definitely not experiencing this issue any more.
