### ISSUE TITLE
Create per-target `.config` file

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#108]
This issue tracks fixing the naming and kconfig issues associated with a single project name as well as the varying configuration which is the result of having multiple targets.

The issue requires changes to:

https://github.com/unikraft/kraftkit/blob/b8eb19f/schema/loader.go#L388

Which should not use the `projectName` but the target name.

Additionally, an associated "`.config`" file should be created, in the format: `.$TARGET_NAME.kconfig` which is then fed to Unikraft via `UK_DEF_CONFIG=path/to/$TARGET_NAME.kconfig`.

**Comment by craciunoiuc** [comment]
Fixed a while ago, each target has it's own config now
