### ISSUE TITLE
`kraft pkg ls` should display size

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/kraftkit#1193]
### Feature request summary

There is nothing that shows the size of an available package that can be downloaded.
Users do not know if they can afford to run a test (especially for the ones using a hotspot)

A new column should be added to `kraft pkg ls` to show the size of each package if it were to be downloaded.

### Related architectures

None

### Related platforms

None

**Comment by nderjung** [comment]
I'll take care of this, as part of the OCI rework.

**Comment by craciunoiuc** [comment]
This was fixed.
