### ISSUE TITLE
Allow custom KraftCloud server URI

### ISSUE THREAD

**Issue by marcrittinghaus** [unikraft/kraftkit#1206]
### Feature request summary

For local Kraftcloud development and on-premise deployments you need to be able to specify a local address (e.g., `http://127.0.0.1:PORT` or `http://company-server.internal:PORT`).

Suggestion is to add a `KRAFTCLOUD_ADDR` environment variable to the existing `KRAFTCLOUD_METRO` and `KRAFTCLOUD_TOKEN` variables. `KRAFTCLOUD_ADDR` takes precedence over `KRAFTCLOUD_METRO` and is used as-is if defined.

### Related architectures

None

### Related platforms

None

**Comment by allenkting** [comment]
Hello! I am a Computer Science student at the University of Texas at Austin. I am currently taking virtualization (CS 360v), and my partner and I would like contribute to this project. We would be interested in being assigned to work on this issue if it is still open!

**Comment by melars74** [comment]
Hi, I'm allenkting's partner for this project. Is this issue still open?

**Comment by craciunoiuc** [comment]
Sorry guys, didn't see your comments, this Issue is mainly internal, and not up for grabs :(

**Comment by craciunoiuc** [comment]
Note: this functionality was already in, through the same mechanism that allows specific metros
