### ISSUE TITLE
Add `-o raw` option for KraftCloud commands

### ISSUE THREAD

**Issue by marcrittinghaus** [unikraft/kraftkit#1207]
### Feature request summary

For Kraftcloud development and debugging as well as to be able to easily retrieve raw information from the server, the `kraft cloud` commands should support a `-o raw` option to output 1:1 the server's JSON response.

This is needed also because `kraft` modifies and hides information even with the `-o json` option. For example, the `created at` field just reports `X days ago` instead of the exact timestamp. Another example, the service group name of an instance is not reported. 

Furthermore, it makes it easy to access new information as soon as they become available from the server, without the need to wait for `kraft` integration.

### Related architectures

None

### Related platforms

None

**Comment by antoineco** [comment]
For information the work on the Go SDK is happening here: https://github.com/kraftcloud/go-sdk/pull/22

This will ensure that `-o json` returns payloads which are faithful to what is documented at [docs.kraft.cloud](https://docs.kraft.cloud/api/v1/). This is however only one part of the story, as enabling a true raw mode will require bypassing current SDK methods.

**Comment by antoineco** [comment]
The last part of the changes needed for the `-o raw` flag will be implemented as soon as https://github.com/kraftcloud/go-sdk/pull/26 makes it into the SDK.

**Comment by antoineco** [comment]
Second large change to the SDK that supports this feature: https://github.com/kraftcloud/go-sdk/pull/26
