### ISSUE TITLE
Add pipeline for building and pushing webinstall image

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#1290]
### Feature request summary

This issue tracks adding a GitHub actions pipeline which, for PRS, tests the installation (and simultaneously attempts to perform an installation), as well as pushing to the OCI repository on successful merges.

### Related architectures

None

### Related platforms

None

**Comment by UjjwalMahar** [comment]
Hi @nderjung can you please explain this more I would like to work on this.

**Comment by craciunoiuc** [comment]
Hey, no worries, I can handle this, it requires setting some tokens and it's easier if I do it 🙈

**Comment by UjjwalMahar** [comment]
Okay sir no problem 😃

**Comment by craciunoiuc** [comment]
This is now fixed, but I will not close as testing also needs to happen.

**Comment by craciunoiuc** [comment]
This should work now
