### ISSUE TITLE
Ephemeral buildkit container fails to consistently spawn with kraft run

### ISSUE THREAD

**Issue by felipehuici** [unikraft/kraftkit#1341]
### Describe the bug

When using kraft run I often get an error similar to:  E  unpacking the image: opening layer: open /Users/fhuici/.local/share/kraftkit/runtime/oci/digests/sha256/09613022ba9985f35083918e11f1e2fd8352183bf5ee761d50c2b88817bc5483: no such file or directory

I notice that if I re-run the command (see output in the other box), sometimes it does work, saying " i  creating ephemeral buildkit container". I'm guessing the issue is that for some reason this buildkit container isn't always spawned, given this is a newly introduced feature, but I don't know if this is what's going on.

I also don't know if this is a mac-only issue.

### Steps to reproduce

Go to the KC examples repo, cd into http-c and run:

kraft run  --plat qemu --arch x86_64 --log-level debug --log-type basic -p 443:8080 .

### Expected behavior

Output such as:
[...]
Powered by Unikraft Telesto (0.16.2~687131d)
Listening on port 8080...
en1: Set IPv4 address 10.0.2.15 mask 255.255.255.0 gw 10.0.2.2

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

macOS

### Relevant log output

```shell
➜  http-c git:(main) ✗ killall qemu-system-x86_64 ; sudo kraft run  --plat qemu --arch x86_64 --log-level debug --log-type basic -p 443:8080 .
No matching processes belonging to you were found
 W  using hardware emulation
 i  pulling unikraft.org/base:latest (x86_64/qemu)
 E  unpacking the image: opening layer: open /Users/fhuici/.local/share/kraftkit/runtime/oci/digests/sha256/e3f208309e226ee8f6bdeca7985d583ea26d1dbae46350ff9f02734cb90f6741: no such file or directory

➜  http-c git:(main) ✗ killall qemu-system-x86_64 ; sudo kraft run  --plat qemu --arch x86_64 --log-level debug --log-type basic -p 443:8080 .
No matching processes belonging to you were found
 W  using hardware emulation
 i  pulling unikraft.org/base:latest (x86_64/qemu)
 E  unpacking the image: opening layer: open /Users/fhuici/.local/share/kraftkit/runtime/oci/digests/sha256/09613022ba9985f35083918e11f1e2fd8352183bf5ee761d50c2b88817bc5483: no such file or directory

➜  http-c git:(main) ✗ killall qemu-system-x86_64 ; sudo kraft run  --plat qemu --arch x86_64 --log-level debug --log-type basic -p 443:8080 .
No matching processes belonging to you were found
 W  using hardware emulation
 i  creating ephemeral buildkit container
 i  #1 [internal] load build definition from Dockerfile
 i  #1 transferring dockerfile: 426B done
 i  #1 DONE 0.0s
 i
 i  #2 [internal] load metadata for docker.io/library/gcc:13.2.0-bookworm
 i  #2 DONE 1.8s
 i
 i  #3 [internal] load .dockerignore
 i  #3 transferring context: 2B done
 i  #3 DONE 0.0s
 i
 i  #4 [internal] load build context
 i  #4 transferring context: 1.80kB done
 i  #4 DONE 0.0s
```

**Comment by craciunoiuc** [comment]
I can't reproduce this anymore on linux/mac
