### ISSUE TITLE
kraft ps reports 0M when not using the -M flag for kraft run

### ISSUE THREAD

**Issue by felipehuici** [unikraft/kraftkit#1371]
### Describe the bug

kraft ps reports 0M when not using the -M flag for kraft run

### Steps to reproduce

run kraft run w/o the -M flag
when finished do kraft ps, look at MEM field, should say 0MiB

### Expected behavior

kraft ps should display whatever the default M value set by kraft is.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

macOS

### Relevant log output

```shell
➜  http-rust1.75-actix-web4 git:(main) ✗ kraft ps
NAME              KERNEL                          ARGS     CREATED         STATUS   MEM   PORTS                   PLAT
admiring_ndakasi  oci://unikraft.org/base:latest  /server  22 minutes ago  running  0MiB  0.0.0.0:8080->8080/tcp  qemu/x86_64
```

**Comment by craciunoiuc** [comment]
This actually happens regardless of the `-M` flag, investigating
