### ISSUE TITLE
Rolling updates of deployments on KraftCloud

### ISSUE THREAD

**Issue by marcrittinghaus** [unikraft/kraftkit#1375]
### Feature request summary

You want to be able to update your deployment on KraftCloud without service interruption. This includes all the instance settings (e.g., amount of memory, env variables, image etc.). The current approach according to [this guide](https://docs.kraft.cloud/guides/features/rolling/) is to:

1. Create a service group
2. Create an instance within the service group

When you want to update:

3. Create another instance within the service group that has the updated settings
4. Wait until the new instance is up and serving requests
5. Drain stop the old instance
6. Delete the old instance, when it has stopped

Since this is very cumbersome to do manually, `kraft cloud` should provide a command or option to perform these steps for the user.

## Specific requirements
Important is that the command must be able to handle **scaled services**. In this case, you don't have one instance but multiple instances within the same service group. This can be set up either manually if the user just created multiple instances (maybe using the `replicas` option) or by using autoscale. Since autoscale instances are managed by the server and cannot be updated by tooling, this issue applies to manually scaled services, only.

To avoid running into quota issues with heavily scaled services, the new `kraft` command should update one instance after the other and not attempt to replace all instances at once.

## Existing work
@nderjung Already started working on this here: 
- https://github.com/unikraft/kraftkit/pull/1187

### Related architectures

None

### Related platforms

None

**Comment by craciunoiuc** [comment]
Done in #1511
