### ISSUE TITLE
`kraft cloud scale remove` requires a service group UUID, which is hard to find

### ISSUE THREAD

**Issue by antoineco** [unikraft/kraftkit#1376]
### Describe the bug

Usability issue: `kraft cloud scale remove` requires a service group _UUID_, but `kraft cloud service get/ls` does not return UUIDs, unless used with `-o list`.

**Comment by craciunoiuc** [comment]
Yeah, I think this is the case of all `get/list` commands. It's just that in this case specifically, an `UUID` is needed

I will mark it `low` priority because right now the only fix is to switch the default printer

**Comment by craciunoiuc** [comment]
I think we need to decide whether it's worth switching to `-o list` as the default for when a single element is present.

Makes sense that a table would be used when you have tens of rows, not much when you have 2-3

**Comment by craciunoiuc** [comment]
This has been fixed a while ago kind of: `kraft cloud scale get` and the rest show lists as default now which have the uuid
