### ISSUE TITLE
If user forgets to add "M" to the -M flag, kraft silently uses default memory amount

### ISSUE THREAD

**Issue by felipehuici** [unikraft/kraftkit#1382]
### Describe the bug

If user forgets to add "M" to the -M flag, kraft silently uses defaults memory amount, which can cause the app to fail without giving the user much indication as to why.

### Steps to reproduce

Run something like:

kraft run --rm -p 1313:1313 --plat qemu --arch x86_64 -M 512 # NOTE: no "M" after 512

on any app that requires more than the default amount of memory (which I think is 64M)

### Expected behavior

kraft should probably give an error, saying that the unit is missing, and stopping, rather than silently continuing, applying (silently again) the memory default, and then potentially failing if the app needs memory, without the user understanding why.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

macOS

### Relevant log output

```shell
% kraft run --rm -p 1313:1313 --plat qemu --arch x86_64 -M 512
 W  using hardware emulation
 i  using arch=x86_64 plat=qemu
[+] pulling unikraft.org/hugo:latest (qemu/x86_64) •••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• 100% [1m 46s]
[+] building rootfs... done!                                                                                                                                    x86_64 [3.1s]
 E  machine fatally exited
```

**Comment by craciunoiuc** [comment]
This happens because no unit defaults to Bytes, and if the size is smaller than 1MB it goes down to 0 because of the division and conversion to int

I will limit the input to at least one `MiB`
