### ISSUE TITLE
Invoking the `--help` command takes time.

### ISSUE THREAD

**Issue by UtkarshVerma** [unikraft/kraftkit#1415]
### Describe the bug

The `kraft` binary processes something even when `--help` is passed. The result is that invoking this flag takes time to run.

```console
$ time kraft --help
kraft --help  0.12s user 0.10s system 22% cpu 0.949 total
$ time podman --help
podman --help  0.02s user 0.03s system 114% cpu 0.042 total
```

`--help` is one of those flags that are run repeatedly when developing apps, especially when no manpage exists. Fixing this would lead to good DX.

### Steps to reproduce

Run `time kraft --help`.

### Expected behavior

The help text is displayed quicker.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/arch

**Comment by craciunoiuc** [comment]
This usually happens if some of the files are not owned by the current user (they are owned by root).

Try deleting everything in `~/.local/share/kraftkit` and `~/.config/kraftkit` and let me know if it is faster

**Comment by UtkarshVerma** [comment]
I did not delete my config and data directories, but I can assure that everything is owned by my user. `ls -lha **/* | grep root` returns empty.

**Comment by craciunoiuc** [comment]
@UtkarshVerma do you, by any chance, have a slow internet and/or high ping? :D

I'm asking because all kraftkit commands do a version check first, see output below:

```
time kraft --help
[...]
kraft --help  0,04s user 0,03s system 35% cpu 0,189 total
```

And without the checks:
```
time kraft --no-check-updates --help
[...]
kraft --no-check-updates --help  0,04s user 0,01s system 149% cpu 0,033 total
```

The plan is to do this check only once a day or so, but it still needs deciding.

Let me know if delay is the same.

**Comment by UtkarshVerma** [comment]
You are indeed right. The update check was the culprit here. I will add an alias to `kraft --no-check-updates` on my machine. Please feel free to close this issue if you don't think any action is required here.

**Comment by craciunoiuc** [comment]
I won't close, a fix is coming to cache the version for speed.
