### ISSUE TITLE
``kraft net create`` fails if network name is too long

### ISSUE THREAD

**Issue by LucaSeri** [unikraft/kraftkit#1456]
### Describe the bug

When trying to create a network, there is a name length limit that is generated by the ``kraftkit`` convention of naming interfaces. On linux, for instance, this limit is 15 characters.

A possible solution would be to have some internal mapping from the network name to some random interface name that adheres to the limit.

### Steps to reproduce

Run:
```bash
kraft net create a-somewhat-longer-name

E  bridge creation for a-somewhat-longer-name failed: numerical result out of range
```

### Expected behavior

For the network to be created

**Comment by LucaSeri** [comment]
This can get even worse, the network name might not be too long, but any generated interface on that network be too long, e.g:
```
kraft net create 12345678901234
```

Now trying to run:
```
kraft run nginx:1.15 --network 12345678901234
```
hangs, because it is unable to find a valid interface to assign to the machine.
This is very hard to debug and the root cause is the way its done here:
https://github.com/unikraft/kraftkit/blob/staging/machine/network/bridge/v1alpha1.go#L272

The generated error in the above case is actually:
`numerical result out of range` - this is the error when an interface name is too long

**Comment by craciunoiuc** [comment]
Easiest thing to do is to add a check limiting to 13 characters (2 left out so appending can work fine)

**Comment by craciunoiuc** [comment]
I can do this now. Fully correct would be to fetch the max length, but this needs to be os-agnostic

**Comment by craciunoiuc** [comment]
I see that the value is past of the glibc headers so not so easy to fetch outside Linux, we'll hardcore for now
