### ISSUE TITLE
Introduce package manager for AMI (Amazon Machine Images)

### ISSUE THREAD

**Issue by razvand** [unikraft/kraftkit#1467]
### Feature request summary

Introduce an AWS package manager for [AMI (Amazon Machine Images)](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html). This would allow native packaging (and therefore listing, pushing, pulling) of AMI images.

### Related architectures

None

### Related platforms

None

**Comment by nderjung** [comment]
Closing in favour of #1468
