### ISSUE TITLE
`kraft fetch` panics immediately

### ISSUE THREAD

**Issue by antoineco** [unikraft/kraftkit#1489]
### Describe the bug

```console
$ kraft fetch
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5557117f0cce]
```

**Comment by craciunoiuc** [comment]
"Fix" here is to hide the command as it is currently broken

**Comment by antoineco** [comment]
Why not just remove it? If it's advertised as deprecated (first message when you run it) _and_ is broken, we might as well just get rid of it.

**Comment by craciunoiuc** [comment]
It sometimes works, but it's very specific, so I don't want to completely erase it 👀
