### ISSUE TITLE
``processtree`` parallel by default if some process has children

### ISSUE THREAD

**Issue by LucaSeri** [unikraft/kraftkit#1533]
### Describe the bug

If we build a tree of processes similar to this:
```
   p1     p2
  / \    /  \
 c1 c2  c3  c4
```

Even if we start the ``processtree`` with ``IsParallel(false)``, the children will still start executing in parallel.

### Expected behavior

Children should execute sequentially

**Comment by craciunoiuc** [comment]
Can you describe what runs in parallel in your example? From what I can see in the code, only the first of multiple children is taken as "ready to execute"

**Comment by LucaSeri** [comment]
Hi @craciunoiuc, see the snippet below:

```go
	childLeft := processtree.NewProcessTreeItem("left", "", func(ctx context.Context) error {
		for {
			log.G(ctx).Printf("left")
		}
	})

	processLeft := processtree.NewProcessTreeItem("left", "", func(ctx context.Context) error {
		log.G(ctx).Printf("executing left")
		return nil
	}, childLeft)

	childRight := processtree.NewProcessTreeItem("right", "", func(ctx context.Context) error {
		for {
			log.G(ctx).Printf("right")
		}
	})

	processRight := processtree.NewProcessTreeItem("right", "", func(ctx context.Context) error {
		log.G(ctx).Printf("executing right")
		return nil
	}, childRight)

	treemodel, err := processtree.NewProcessTree(
		ctx,
		[]processtree.ProcessTreeOption{
			processtree.IsParallel(false),
			processtree.WithRenderer(
				log.LoggerTypeFromString(config.G[config.KraftKit](ctx).Log.Type) != log.FANCY,
			),
			processtree.WithFailFast(true),
			processtree.WithHideOnSuccess(true),
		},
		processLeft,
		processRight,
	)

	if err != nil {
		return err
	}

	if err := treemodel.Start(); err != nil {
		return err
	}
```

If you look at the logs, you will see "left" and "right" alternating:
```
 i  left
 i  left
 i  right
 i  right
 i  left
 i  right
 i  right
 i  left
```

**Comment by craciunoiuc** [comment]
@LucaSeri  Check here https://github.com/unikraft/kraftkit/blob/staging/tui/processtree/processtree.go#L256

I think this happens because each process in a tree is parallel. In there you have a 2 trees with 2 roots in a list. Each of them is started as they have a children each.

Diagram looks like this currently:
```
  p1     p2
  |      | 
 c1      c1
 ```
 
 To test correctly try creating 2 children for each `childLeft1`/`childLeft2` and `childRight1`/`childRight2`

**Comment by LucaSeri** [comment]
@craciunoiuc this was a misunderstanding on my end.
The top-level processes in the ``processtree`` execute in parallel, but the children within each sub-tree are executed sequentially.
Tested this and it works as expected.
Closing this as there is nothing to be done.
