### ISSUE TITLE
`catalog/examples/python3.12-flask3.0-sqlite`: gives: `panic: assignment to entry in nil map`

### ISSUE THREAD

**Issue by cosmin1805** [unikraft/kraftkit#1615]
### Describe the bug

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
Linux unikraft 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Running on a proxmox VM

### Steps to reproduce

```console
kraft run --rm -p 8080:8080 --plat qemu --arch x86_64 -M 1024M .
```

### Expected behavior

The example to start

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian

### Relevant log output

```shell
panic: assignment to entry in nil map

goroutine 321 [running]:
kraftkit.sh/internal/cli/kraft/run.(*RunOptions).prepareRootfs.func1({0x21dc8b8?, 0xc006eef050?})
        /__w/kraftkit/kraftkit/internal/cli/kraft/run/utils.go:401 +0x13b
kraftkit.sh/tui/processtree.(*ProcessTree).Init.(*ProcessTree).waitForProcessCmd.func2()
        /__w/kraftkit/kraftkit/tui/processtree/processtree.go:329 +0xb4
github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1.1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:294 +0x29
created by github.com/charmbracelet/bubbletea.(*Program).handleCommands.func1 in goroutine 316
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.25.0/tea.go:293 +0x139
```
```

**Comment by Nyrox** [comment]
Fresh install on osx gives the same error on both the node21-express and http-rust1.75 examples

**Comment by craciunoiuc** [comment]
This is fixed in latest staging 🙏
