### ISSUE TITLE
Do not add default manifest if no manifests exist and sourcing

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#168]
This issue tracks a fix such that the list of Unikraft manifests does not include the default manifest if empty and the `kraft pkg source` command is used. Currently, if the list is empty and sourcing command is used, the default source is added preemptively.

**Comment by mdsahiloss** [comment]
@nderjung I think This issue has been fixed.

**Comment by craciunoiuc** [comment]
Yes, this is fixed now, I will close it
