### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by vaastav** [unikraft/kraftkit#171]
Hi I have been trying to install KraftKit and running into this error:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 kraftkit : Depends: libgit2-dev (>= 1.1) but 0.28.4+dfsg.1-2 is to be installed

I am on Ubuntu 20.04 and I already have libgit2-dev installed so not sure what to do.

**Comment by junyang-zh** [comment]
I have the same issue when installing from apt.

**Comment by craciunoiuc** [comment]
This is the same issue as #179 and is currently handled by someone in the community

Sorry for the late response. Best you can do right now is to run in a container.

**Comment by craciunoiuc** [comment]
This is fixed now
