### ISSUE TITLE
Support building static library

### ISSUE THREAD

**Issue by mkroening** [unikraft/kraftkit#175]
For my [`unikraft-rs`](https://github.com/mkroening/unikraft-rs) initiative, I am building Unikraft as a static library to then link it using Cargo.

Currently, I am assembling a static library myself. For the initial approach, see [`mkroening/unikraft-static`](https://github.com/mkroening/unikraft-static) as well as @razvand's initial instructions, which are linked there.

I am currently filtering all entries in `build` with this predicate:
```rust
(file_type.is_file()
    && file_name.starts_with("lib")
    && file_name.ends_with(".o")
    && !file_name.ends_with(".ld.o"))
```

Which are then linked using `ar rcs libunikraft.a <OBJECT_FILES>`.

It would be awesome, if KraftKit supported building static libraries, so I would not have to handle the complexity of ensuring clean builds in my build script myself.

What do you think?

**Comment by craciunoiuc** [comment]
I'm all about this, but let me know first if there's an already existing command for `make` to do this

**Comment by mkroening** [comment]
Not yet. I am currently working on upstreaming one:

 - https://github.com/unikraft/unikraft/pull/715

**Comment by craciunoiuc** [comment]
nice, okay, then we can come back to this once it's upstream 🙏

**Comment by mkroening** [comment]
Closing in favor of

- https://github.com/unikraft/unikraft/pull/957
