### ISSUE TITLE
Support environments without TTY

### ISSUE THREAD

**Issue by mkroening** [unikraft/kraftkit#178]
When running on GitHub Actions, I get:

```console
$ kraft pkg update
open /dev/tty: no such device or address
```

**Comment by mkroening** [comment]
This also makes it impossible to run in Docker, be it in a `Dockerfile` or interactively, without simulating TTY.

**Comment by craciunoiuc** [comment]
This kinda works now, but not completely.

For example, `docker build` still fails with kraft commands, but wrapping like this works:
```
true | (setsid kraft pkg update) 2>&1 | cat
```

The problem probably stems from bad auto-detection of the environment.

**Comment by nderjung** [comment]
I have a fix for KraftKit for this, which relies on:

https://github.com/charmbracelet/bubbletea/pull/643

**Comment by craciunoiuc** [comment]
They merged and we bumped it, time to close it
