### ISSUE TITLE
Remove libgit2 dependency

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#179]
This issue tracks removing the [`git2go` dependency](github.com/libgit2/git2go). KraftKit currently makes use of `git2go` which use of an external `libgit2` shared object dependency which is used to calculate the progress of a clone (so when you run `kraft pkg pull` and it resolves to a git repo, the progress bar of the clone is shown).  Whilst useful, this dependency issue causes installation issues and is preventing some new users from using KraftKit.

The use of `git2go` is used only in one location in KraftKit:

https://github.com/unikraft/kraftkit/blob/staging/manifest/pack_pull_git.go#L37

The way to approach a rewrite is to use the almost ubiquitious use of [`go-git/v5`](github.com/go-git/go-git).  [Here's an example of a progress bar based on `v4`](https://gist.github.com/tyru/82cae8bad2b116f442d08eeef456e23e).

**Comment by craciunoiuc** [comment]
Currently handled by someone in the community

**Comment by nderjung** [comment]
Re-opening this issue. Statically compiling libgit2 brought more problems and should just be removed entirely. See https://github.com/unikraft/kraftkit/pull/458 for reference.

libgit2/git2go is now also used for authentication over ssh, we can also be accomplished with go-git:

https://github.com/go-git/go-git/blob/1dbd729a387edb61c89f088cd68040085e6c81bb/plumbing/transport/ssh/auth_method.go#L183-L204

**Comment by craciunoiuc** [comment]
Attempt number # 3 at solving this, @antoineco are you up for the task 👀
