### ISSUE TITLE
kraft run 9P security model

### ISSUE THREAD

**Issue by Firobe** [unikraft/kraftkit#1934]
### Describe the bug

Using 9P with qemu requires passing a security model to manage how ownership and other attributes is translated on files on the host.

`kraft run -v ...` exclusively uses the `passthrough` model:

https://github.com/unikraft/kraftkit/blob/f02a533111e7a08c4373c01dcc9b2b1980a3ea3a/machine/qemu/v1alpha1.go#L331-L344

To quote [QEMU's documentation](https://wiki.qemu.org/Documentation/9psetup#Starting_the_Guest_directly):

> passthrough: Files are stored using the same credentials as they are created on the guest. This requires QEMU to run as root and therefore using "passthrough" security model is strongly discouraged, especially when running untrusted guests!

And indeed, a simple native unikernel creating a new file on a mounted filesystem, if run without `sudo`, crashes because the file cannot be created.

What's the rationale for using `passthrough` instead of for example the recommended `mapped-xattr` model?

> mapped-xattr: Some of the file attributes like uid, gid, mode bits and link target are stored as file attributes. This is probably the most reliable and secure option.

It does seem to work well with direct invocations of qemu instead of using `kraft run`, this time without requiring `sudo`.

**Comment by craciunoiuc** [comment]
Probably passthrough was the more including example, but if this avoids using `sudo` I'm for it.

I'll open a PR with your suggestion. Thanks!

**Comment by Firobe** [comment]
Thank you for the answer and the fix!
