### ISSUE TITLE
Switch goreleaser to use github for changelog

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#203]
### Feature request summary

Since we are using GitHub and features are well-defined as issues and through PRs, we should switch the goreleaser changelog method to use [`github` over `git`](https://github.com/unikraft/kraftkit/blob/staging/.goreleaser-stable.yaml#L4). This will associate PR creators in the release message as well as the title of PR.

See: https://goreleaser.com/customization/changelog/

### Related architectures

None

### Related platforms

None

**Comment by craciunoiuc** [comment]
Already fixed
