### ISSUE TITLE
Deprecate `unikraft.NameTypeVersion` in favour of `fmt.Stringer`

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#268]
### Feature request summary

Implementations which utilize `unikraft.Nameable` should instead return an `fmt.Stringer` interface such that the canonical version of their name can be appropriately set and used across KraftKit.  This would then alleviate the use of the wrapper method [unikraft.TypeNameVersion](https://github.com/unikraft/kraftkit/blob/staging/unikraft/type.go#L111), which would return an incorrect value if wrapping a target.Target input which is unikraft.Nameable.

### Related architectures

None

### Related platforms

None

**Comment by afzal442** [comment]
After digging into it, I think we can do as below;

Modify the existing implementation of the unikraft.Nameable interface to implement the fmt.Stringer interface 

```
type Nameable interface {
    Type() ComponentType
    Name() string
    Version() string
    String() string
}
```
```
func TypeNameVersion(entity Nameable) string {
    // ...
}
```
to
```
func (entity Nameable) String() string {
```

Replace any usage of unikraft.TypeNameVersion() with `fmt.Sprintf("%s", object.XYZ())`

LMK! Thanks

**Comment by nderjung** [comment]
Hi @afzal442, thanks for having a look at this.

The way to approach this, I think, would be to add the `fmt.Stringer` interface directly to the `Nameable` interface, i.e.:

```diff
  type Nameable interface {
+   fmt.Stringer
```

The above implies `String()`. In a PR that solves this issue, and in a single commit, instances of `unikraft.TypeNameVersion(xyz)` should be removed and replaced with `xyz.String()`.

**Comment by afzal442** [comment]
Gotcha. I am into it. Thanks

**Comment by rpunjani** [comment]
Hello! I'm a student at UT Austin taking a course in virtualization, and I wanted to see if I could contribute to this issue. Is this issue still open, and if so, can I get it assigned to me. Thanks.

**Comment by nderjung** [comment]
Hi @rpunjani, apologies we're closing this issue as it is no longer applicable.
