### ISSUE TITLE
Reliably check for in-container run via `Makefile`

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#270]
### Feature request summary

The addition to check for heterogeneous container runtimes in e83d0f5b733e2e4eb29e5b7a9858e906a674782d in the [`Makefile`](https://github.com/unikraft/kraftkit/blob/staging/Makefile#L63) does not work in all cases. Testing a bare metal Debian 11 with k3s/containerd (`v1.25.6+k3s1`) does not work. Instead the host system's `/proc/1/cgroup` returns the following:
```
0::/init.scope
```
Whilst the container returns the following:
```
0::/
```
This results in the inability to spawn a developer environment on the host. 

This issue tracks a more long-term, stable, cross-container runtime solution to enable invocation of the build-system both external to a container and internal to one.

### Related architectures

None

### Related platforms

None

**Comment by antoineco** [comment]
It's probably safer to remove the cgroup check then.

`DOCKER` already defaults to a non-empty value, and we should be covered by passing this in container commands:

https://github.com/unikraft/kraftkit/blob/6043bcdb3913cc56494ce07a80d401a242a69596/Makefile#L42

I originally implemented this change in another repo which _didn't_ pass `-e DOCKER=` in container commands.
