### ISSUE TITLE
Selecting a run target always results in "unknown target"

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#271]
### Describe the bug

This issue tracks fixing a bug where the selection of a target via `kraft run` always returns `unknown target`.

GitHub-Related: #268
GitHub-Related: #265

### Expected behavior

Running `kraft run` without any input should prompt the user to select a target. Upon selection, that target should be invoked and executed.

**Comment by mdsahiloss** [comment]
@nderjung I would like to work on it, Can you assign it to me.

**Comment by mdsahiloss** [comment]
@nderjung It seems like enhancement has already been made https://github.com/unikraft/kraftkit/blob/staging/cmd/kraft/run/run.go#L198 to resolve this issue.

**Comment by craciunoiuc** [comment]
Actually this still happens, tested today with the latest changes on staging

**Comment by craciunoiuc** [comment]
Somewhat related also to #199

**Comment by craciunoiuc** [comment]
This is fixed now. Probably it was not fixed back then because of some hard-to-fix cmdfactory errors that are now done.

I can successfully pick from multiple options and it will select the correct one.

It is worth noting though that not providing any plat/arch will default to `<qemu>/<host_arch>`
