### ISSUE TITLE
Statically link binaries

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#31]
This issue tracks statically linking all binaries available in KraftKit.

The major overhead here is the use of github.com/libgit2/git2go which depends on `libgit2-dev`.

The reason for using this library is that it offers progress callback (so cloning a repo can be monitored).  If native Go library which implements Git can offer the same, this should be used as an alternative.  Otherwise, this issue also explores statically linking against the `libgit2-dev` shared library https://github.com/libgit2/libgit2

**Comment by craciunoiuc** [comment]
No longer needed as the dependency was removed and there are no other dependencies
