### ISSUE TITLE
Docker OCI handler

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#358]
## Feature request summary

This issue tracks adding a Docker OCI handler into KraftKit which will enable Docker users to list, pull, package and run OCI unikernel images using the aforementioned container runtime system.

To approach this, the implementer must introduce a new structure, `DockerHandler`,  inside of `oci/handler/docker.go` which implements the `oci.handler.Hancler` interface:

https://github.com/unikraft/kraftkit/blob/df0a3ac19eebac8b385d5c043370c6a7ccfdbf73/oci/handler/handler.go#L15-L50

A new constructor method is also required which instantiates a connection to the docker daemon, something along the lines of:

```go
func NewDockerHandler(ctx context.Context, address string) (*DockerHandler, error)
```

Additionally, for a KraftKit user, an additional configuration option should be made available in [KraftKIt's global configuration file](https://github.com/unikraft/kraftkit/blob/staging/config/config.go#L17) which allows the user to point to the relevant socket:

```go
DockerAddr string `yaml:"docker_addr,omitempty" env:"KRAFTKIT_DOCKER_ADDR" long:"docker-addr" usage:"Address of Docker daemon socket" default:""`
```

Finally, the OCI Package Manager must detect whether the socket has been set and whether to instantiate the Docker handler, which is done by [adding an `if else` statement](https://github.com/unikraft/kraftkit/blob/df0a3ac19eebac8b385d5c043370c6a7ccfdbf73/oci/manager.go#L59-L76) to the `handler` method:

https://github.com/unikraft/kraftkit/blob/df0a3ac19eebac8b385d5c043370c6a7ccfdbf73/oci/manager.go#L59-L76

For example:

```go
} else if dockerAddr := config.G[config.KraftKit](ctx).DockerAddr; len(dockerAddr) > 0 {
 	handle, err := handler.NewDockerHandler(ctx, dockerAddr) 
 	if err != nil { 
 		return nil, nil, err 
 	} 
  
 	return ctx, handle, nil 
}
```

### Reference material
 - [KraftKit's containerd handler implementation](https://github.com/unikraft/kraftkit/blob/staging/oci/handler/containerd.go);
 - [Example usage of Docker Go client](https://github.com/moby/moby/blob/5bf405b2afea6daf3960ad91583b0d290afd843f/client/client.go#L27-L39);
 - [KraftKit commit introducing OCI and containerd handler](https://github.com/unikraft/kraftkit/commit/df0a3ac19eebac8b385d5c043370c6a7ccfdbf73).
 - [Docker Go SDK Example](https://docs.docker.com/engine/api/sdk/examples/)

**Comment by rpunjani** [comment]
Hi, I'm a student from the University of Texas at Austin interested in working on this issue for my virtualization class (CS 360V). I was wondering what the status of this issue is and if there's any other information that could be helpful in the implementation of this feature. Thanks.

**Comment by nderjung** [comment]
Hi @rpunjani, unfortunately after investigating the Docker source code and someone attempting this implementation, we discovered that this was in fact impossible.  Please feel free to look through our other list of project ideas.

Unfortunately, this implementation is not possible because it is not possible to set a custom `OS` and `Architecture` of images.  These are forcefully set to `os.GOOS` and `os.GOARCH`, respectively.
