### ISSUE TITLE
Run workflows on updated workflows

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#386]
## Describe the bug

The dependabot action for updating workflows should also run the respective workflow to confirm that the upgrade works.

This can be alleviated by providing an include for the specific workflow which negates the original negation, for example, adding the workflow to the list:

https://github.com/unikraft/kraftkit/blob/eae82bb14c335f23454ac67af42ba1c85876eb2a/.github/workflows/build.yaml#L9

This, and any PR from a contributor who does update the relevant workflow, this should also be tested of course.

Once a fix for this has been upstreamed we can rebase (and re-run):

 - #378 
 - #379 
 - #380
 - #381

**Comment by antoineco** [comment]
Good that you mention it, I've been wondering why we have this exclusion in place. Is there a good reason not to run workflows on every PR to start with, besides "saving cycles"?

**Comment by nderjung** [comment]
I believe it's just fine-tuning at this point.  Actions is a bit hard to test completely, @craciunoiuc has a local setup where he can test things (or some private repo where he's doing things to a staging env). Workflows should only run when appropriate, e.g. the git format check only needs to run on PRs, the build needs to only run when Go code is changed, etc.

**Comment by antoineco** [comment]
ACK. In that case I agree with the suggested approach of explicitly including "self" in each workflow 👍

**Comment by craciunoiuc** [comment]
I opened a PR that should fix this issue + other things: <https://github.com/unikraft/kraftkit/pull/401>

**Comment by antoineco** [comment]
Closed by #401
