### ISSUE TITLE
Web install shell script

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#39]
This issue tracks a series of support files which represent a shell script which is served at https://get.kraftkit.sh.  The script should will be retrievable via:

```shell
curl --proto '=https' --tlsv1.2 -sSf https://get.kraftkit.sh | sh
```

The script should detect the host OS, (linux distribution if applicable), and provide a guided installation which offers to install KraftKit using either the native package manager or by downloading the latest binary.  Checksumming should be embedded in the script.

The structure of the addition should resemble something like:

```
support/webinstall
├── Dockerfile  # Build environment
├── go.mod      # This is a small Go program HTTP server that dynamically injects relevant information into install.sh
├── install.sh  # The actuall installation script which is served
├── main.go     # The Go HTTP server
└── Makefile    # Build instructions
```

**Comment by craciunoiuc** [comment]
Merged some time ago 👯
