### ISSUE TITLE
Configurable output format

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#4]
This issue tracks adding a configurable output format engine within KraftKit and related commands which produce an informational output, for example `kraft pkg ls` or `kraft pkg info`.

Task list:

 - [ ] Investigate how `kubectl get -o`'s output formatter works, it is quite configurable, e.g.:
   ```
   -o, --output='': Output format. One of:
       json|yaml|wide|name|custom-columns=...|custom-columns-file=...|go-template=...|go-template-file=...|jsonpath=...|jsonpath-file=...
   ```
 
- [ ] The implementation should migrate the use of the existing tool [`tableprinter`](https://github.com/unikraft/kraftkit/blob/staging/utils/table_printer.go) and use instead a more relevant library for outputting formatted data.

- [ ] A global option should be introduced into `kraftkit.sh/config` (`Output`) such that the format can be switched;

- [ ] Log output format be adjusted to the desired format when its set to `json`, overriding `log.type`.

- [ ] All tabular data should use a common interface such that its visible output can be adjusted dynamically and without requiring each instance to be reworked.

**Comment by mdsahiloss** [comment]
@nderjung I would like to work on it, Can you assign it to me :)

**Comment by nderjung** [comment]
Hi @MdSahil-oss please feel free to tackle the issue! When ready, please submit a PR or feel free to reach out on Discord to discuss further.

**Comment by mdsahiloss** [comment]
Hi! @nderjung I've started working on it :)

**Comment by mdsahiloss** [comment]
Note: **How `kubectl get -o` is implemented in kubectl :- https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/get/get.go#L194**

**Comment by nderjung** [comment]
Upon implementation, tests should default to JSON output for better parsing. See https://github.com/unikraft/kraftkit/pull/405/files#r1180682845
