### ISSUE TITLE
Add timestamp toggle from config

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#41]
This issue tracks the ability to toggle timestamps on the logger via the configuration option:

https://github.com/unikraft/kraftkit/blob/47f6b3c73b84d747f089c8061c04cda4062deb2f/config/config.go#L69

The adjusment should adopt the [option design pattern](https://www.sobyte.net/post/2022-01/golang-patterns/).

**Comment by mdsahiloss** [comment]
@nderjung I can work on it, If this issue is still to be resolved

**Comment by craciunoiuc** [comment]
Fixed in #160 actually
