### ISSUE TITLE
bug(e2e): `kraft version` fails in GitHub actions workflow

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#411]
### Describe the bug

The e2e test for `kraft version` fails since the merge of #410. This is due to the fact that `make kraft` introduces a longer (more complex) version pattern that the e2e test is not capable of parsing, which results in a failure.

An argument for a solution/fix is to make the test simpler such that it simply detects that a single line starting with `kraft` is emitted after invoking `kraft version`.

### Expected behavior

The e2e test for `kraft version` should pass with binaries which are built via `make kraft`.

**Comment by antoineco** [comment]
It actually fails because the `version` part is missing:

```diff
+ kraft v0.5.0-75-g7bdcf59-2-g0317a8f (0317a8f)
- kraft  (0317a8f)
```

It's an indicator that `make` isn't populating it correctly:

https://github.com/unikraft/kraftkit/blob/8fb2ec33764509657df1ceb1c8a8856b06865e83/Makefile#L34

Investigating.
