### ISSUE TITLE
Print output for e2e tests which error

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#415]
### Feature request summary

It would be good to see the output of the invoked command when an e2e fails which can help get a sense of what went wrong. At the moment this is hidden away.

### Related architectures

None

### Related platforms

None

**Comment by antoineco** [comment]
You're reading my mind! I was about to push something to fix that.

It seems like gomega dumps the object in failure reports by default: https://github.com/onsi/gomega/blob/05dc99a168f129346fed13bda9967a7a4b352476/matchers/have_occurred_matcher.go#L33-L35

I'll write an error type around `exec.ExitError` which dumps `err.Stderr` while pretty-printed via `err.GomegaString()`.
