### ISSUE TITLE
Ignore commit message line lengths for URL citations

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#452]
Checks on Git commit messages can fail for embedded URL citations which exceed 75 characters in length.

It is possible to test for these lines because they always start with the regular expression pattern `\[\d+\]:\shttp`.  ([See example](https://github.com/unikraft/kraftkit/pull/443/commits/8b332ed8e64f5918a887eeff838629c90c6b7738)).

This issue tracks ignoring such lines which start with this pattern.

_Originally posted by @nderjung in https://github.com/unikraft/kraftkit/issues/443#issuecomment-1528996157_

**Comment by craciunoiuc** [comment]
For now the max commit message rule should stay fixed, and we do exceptions based specific PRs/commits. Two reasons for this:
 * Regex is almost unmaintainable 😅
 * There might be more rule exceptions that we didn't think about (Signed-off messages from people with long names for example)
