### ISSUE TITLE
Release binaries are dynamically linked against the outdated libssl1.1

### ISSUE THREAD

**Issue by antoineco** [unikraft/kraftkit#457]
### Description

`make kraft` inside the devenv container produces an executable that is dynamically linked against `libssl1.1`.
By extension this includes **release binaries** (tested with v0.5.1).

This is a problem because the last Ubuntu release that included this version was 20.04 LTS:
- https://packages.ubuntu.com/search?keywords=libssl1.1
- https://packages.ubuntu.com/search?suite=focal&arch=any&searchon=contents&keywords=libssl.so.1.1

```console
$ ldd dist/kraft
        linux-vdso.so.1 (0x00007fffb89b5000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0128905000)
        libssh2.so.1 => /lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f01288c1000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f01288bc000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f01288a7000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f01286a2000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f012824f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0128231000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f0128914000)
```

`kraft` being a user-oriented program, we must expect people to be running it on modern operating systems.

**Comment by nderjung** [comment]
This is a very similar reason for why we're statically compiling with libgit2-dev, aka to prevent a version mismatch or to install additional tools on the host.

A solution is to compile against much older binaries thanks to backwards compatibility (we hope) of shared object libraries and enforce (via, e.g. APT install-recommends) libraries during kraft's installation.

**Comment by antoineco** [comment]
The libgit2 issue is long solved, but after upgrading to Ubuntu 23.04 yesterday I no longer have a solution for running Kraftkit locally. I think this is going to become urgent really soon.

I'm looking into upgrading the build environment as we speak.

**Comment by antoineco** [comment]
Just for the record, here is `kraft` built on Ubuntu 23.04 against `libssl-dev` 3.0.8:

```console
$ ldd dist/kraft
        linux-vdso.so.1 (0x00007ffc1d9a4000)
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f69b86ff000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f69b82ac000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f69b80a7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f69b87ae000)
```

**Comment by antoineco** [comment]
There is apparently a way to install libssl1.1 in more recent Ubuntu versions (22.04 onward), but this is neither supported not something we can expect users to be doing on their machine: https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory
