### ISSUE TITLE
Parse standard `Makefile.uk` variables

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#464]
This issue tracks the parsing of standard Unikraft `Makefile.uk` variables and populating the [`lib.LibraryConfig`](https://github.com/unikraft/kraftkit/blob/staging/unikraft/lib/library.go) structure with oustanding attributes. This includes:

 - `LIB${LIBNAME}_URL` - The origin library for the microlibrary;
 - `LIB${LIBNAME}_VERSION` - The version of the origin library;
 - `LIB${LIBNAME}_BASENAME` - The base name of the microlibrary (maybe? It's not completely standard but it used a lot);
 - `LIB${LIBNAME}_COMMIT` - Only used for commit references when `_VERSION` is not used.

**Comment by camnwalter** [comment]
Hi, I'm a computer science student at the University of Texas at Austin, and my partner and I would like to contribute and solve this issue.  We are interested in working on this if it is still open. Thank you.

**Comment by nderjung** [comment]
Hi @camnwalter, apologies, this is a lingering issue and is both complete and also now deprecated.  However, there is a tangental issue which I have just written up in #1531.
