### ISSUE TITLE
Spit `ui.paraprocess` logs into normal stdout via `tea.Printf`

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#52]
This issue tracks the ability to simultaenously output logs via [`bubbletea`](https://github.com/charmbracelet/bubbletea)'s `Printf` method such that if an error occurs it is retrievable through the user's terminal.  For now, the user interface hides this by truncating the build log and this is not helpful if a larger error occurs.  To mitigate against this, simultaneously outputing this way (which would be hidden via `bubbletea`'s UI window mechanism) so we can have the progress bar print still at the top.

This issue tracks this implementation fix.

**Comment by craciunoiuc** [comment]
This is no longer relevant, as simpler methods of printing exist, like `basic`/`json`/others which do not hide output
