### ISSUE TITLE
No targets selected to build

### ISSUE THREAD

**Issue by gabrielmocanu** [unikraft/kraftkit#563]
### Describe the bug

Not actually a bug, but it's confusing after running `kraft build`.
It seems that everything worked, but actually, it didn't build at all.

### Steps to reproduce

```bash
git clone --depth=1 https://github.com/unikraft/app-helloworld.git;
cd app-helloworld;
# Make sure to have a different platform for x86_64 different than `qemu`, for example `kvm`
kraft build --plat qemu --arch x86_64;
# It will end up like this
```
![image](https://github.com/unikraft/kraftkit/assets/34304856/d46991e1-1d98-4502-aec9-00dfc071fd3f)

### Expected behavior

It should prompt a more obvious error, maybe with a red message.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian

**Comment by nderjung** [comment]
This solved via the rename in https://github.com/unikraft/app-helloworld/pull/17
