### ISSUE TITLE
`kraft build` for a specific target throws up a lot of warnings

### ISSUE THREAD

**Issue by gabrielmocanu** [unikraft/kraftkit#565]
### Describe the bug

`kraft build` for a specific target throws up a lot of warnings for the other targets that are present in the `kraft.yml` file.

### Steps to reproduce

```
git clone --depth=1 https://github.com/unikraft/app-helloworld.git;
cd app-helloworld;
kraft build --plat qemu --arch x86_64;
```
![image](https://github.com/unikraft/kraftkit/assets/34304856/0975f448-5d9f-4c3f-b442-1dae7bada3f1)

### Expected behavior

Not showing up with any warning.

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian

**Comment by nderjung** [comment]
We should down grade the warning to an internal debug message :)

**Comment by craciunoiuc** [comment]
I think the real fix would be to filter targets before `NewProjectFromOptions`, but we can do `debug`, it's okay.
