### ISSUE TITLE
Added features to KraftKit devcontainer

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#579]
### Feature request summary

This issue tracks several additional features to the devcontainer for the KraftKit repository, specifically:
* Adding the `dist/` folder in the environmental PATH variable, such that following a successful `make kraft`, the binary is immediately usable;
* Adding Golang extension to access the language server;
* Adding the build tools from the base environment and the QEMU binaries into the `myself-full` environment such that using `kraft run -W` works without added installation.

### Related architectures

None

### Related platforms

None

**Comment by craciunoiuc** [comment]
This requires a new Dockerfile that copies all the content of `myself-full` and `base` into a new image. The other two items should be easy to do.
