### ISSUE TITLE
Hypervisor error when running using WSL2/VMs

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/kraftkit#592]
### Describe the bug

Using `kraft run` in a virtual machine sometimes errors with `could not determine hypervisor and system mode`, even when disabling acceleration `-W`.

### Steps to reproduce

1. Run on WSL
2. Build an image
3. `kraft run -W nginx-qemu_x86_64`

### Expected behavior

It should run with `-W` and error out without it

### Which architectures were you using or does this bug affect?

x86_64

### Which operating system were you using or does this bug affect?

linux/debian

**Comment by antoineco** [comment]
As an additional note, acceleration is supported and enabled out of the box under WSL2, so both modes should work in such environment.

**Comment by craciunoiuc** [comment]
This should be fixed now, @antoineco can you check?

**Comment by iori2333** [comment]
I'm using WSL2 on Windows 10. I built kraft myself using current staging branch, but it didn't work.
![图片](https://github.com/unikraft/kraftkit/assets/81511507/237232c7-e2be-418f-bb51-80b1bccd3a39)

**Comment by iori2333** [comment]
It works fine if I use start qemu from command line.
![图片](https://github.com/unikraft/kraftkit/assets/81511507/2cf9e7ca-b37d-4dc1-bfec-107ac6024d44)

**Comment by craciunoiuc** [comment]
Hmm, this is interesting @iori2333, I will try to find a wsl system to try kraftkit out

This is the function that does the detection: <https://github.com/unikraft/kraftkit/blob/6e780b405be6e59c0cfc9a997eb281dab90aec6d/machine/platform/detect.go#L109>

Can you confirm that `/proc/modules` and `/proc/cpuinfo` do not contain the info we are searching for?
Furthermore, could you please post their contents here so we can see the format? It would be greatly appreciated 🙏 

It should find `QEMU Virtual CPU` in `/proc/cpuinfo` in order to work.

**Comment by iori2333** [comment]
@craciunoiuc Yes, I checked `/proc/cpuinfo` and it doesn't contain `QEMU Virtual CPU`. Microsoft kernel in WSL2 is not built with kvm support and thus `/proc/modules` is empty.

Here's the content of `/proc/cpuinfo`:
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 80
model name      : AMD Ryzen 7 5800H with Radeon Graphics
stepping        : 0
microcode       : 0xffffffff
cpu MHz         : 3193.879
cache size      : 512 KB
physical id     : 0
siblings        : 16
core id         : 7
cpu cores       : 8
apicid          : 14
initial apicid  : 14
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr arat umip vaes vpclmulqdq rdpid fsrm
bugs            : sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 6387.75
TLB size        : 2560 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 48 bits physical, 48 bits virtual
power management:

...
```

**Comment by craciunoiuc** [comment]
Hmm, then it seems that the last possible check we can do is to actually run qemu and fetch the output

```
➜  ~ qemu-system-x86_64 -accel help
Possible accelerators: kvm, xen, hax, tcg
```

If tcg is detected, then it indeed can run in emulation mode.

In the meantime, so you can still use kraft, just change the line below:
<https://github.com/unikraft/kraftkit/blob/6e780b405be6e59c0cfc9a997eb281dab90aec6d/machine/platform/detect.go#L189>

To:
`return PlatformQEMU, SystemGuest, nil`

**Comment by antoineco** [comment]
@craciunoiuc why are you suggesting that we look for `QEMU Virtual CPU` inside the cpuinfo?
iori2333 runs WSL, and WSL is not a QEMU machine itself.

WSL2 only supports KVM on Windows 11, not Windows 10:

> `nestedVirtualization` (boolean) Boolean to turn on or off nested virtualization, enabling other nested VMs to run inside WSL 2. **Only available for Windows 11**.
>
> -- https://learn.microsoft.com/en-us/windows/wsl/wsl-config

(Parenthesis: The fact that a module isn't listed isn't an indicator that a functionality does not exist in the kernel. For instance, the WSL kernel has all its functionalities compiled in, as opposed to being distributed as loadable modules.)

**Comment by craciunoiuc** [comment]
Yeah, exactly, that's why if all checks fail we need to look in qemu itself to see if it has virtualisation support.

For nested virtualisation it should be fine, because we check directly for `/dev/kvm`

**Comment by antoineco** [comment]
Do we really need that check though? Is it even possible that QEMU does not support TCG at all?

**Comment by craciunoiuc** [comment]
Yup, our previous build of qemu had the `--disable-tcg` flag passed to it, so you never know 😓 

Now that I think of it, there's always a chance that there is a `/dev/kvm` on the system, but the qemu binary has no kvm support, so this should be an additional step I think, before `DetectPlatform`, maybe `DetectQemu`

**Comment by craciunoiuc** [comment]
@iori2333 can you try again with the latest pre-release? It should work now

@antoineco also

**Comment by iori2333** [comment]
> @iori2333 can you try again with the latest pre-release? It should work now
> 
> @antoineco also

Thanks, it works fine now!
