### ISSUE TITLE
Add repository documentation within top-level `docs/` directory

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#61]
This issue tracks the addition of KraftKit's documentation to be stored within a top-level `docs/` folder.

The WIP documentation for KraftKit is located at: https://hackmd.io/@unikraft/rJ90L-rK9

The `docs/` folder should roughly contain the following:

- [ ] #62
- [ ] #63
- [ ] #64
- [ ] #65
- [ ] #66
- [ ] #67
- [ ] #68
- [ ] #69
- [ ] #70
- [ ] #71
- [ ] #72
- [ ] #75
- [ ] #76
- [ ] #77

Ultimately, these files should be cloned and dropped within Unikraft's main [`docs`](https://github.com/unikraft/docs) repository such that they are propagated out of the repository and online onto https://unikraft.org.

**Comment by craciunoiuc** [comment]
might be good as part of `Google Season  of Docs`

**Comment by craciunoiuc** [comment]
The cake is a lie
