### ISSUE TITLE
Replace file path separator from `/` with `filepath.Separator`

### ISSUE THREAD

**Issue by craciunoiuc** [unikraft/kraftkit#627]
### Describe the bug

there are currently `26` usages of "/" instead of `filepath.Separator`.
One should go over each of them and replace in the context that makes sense.

This would currently fail on Windows, if it were to be tried there.

**Comment by fnknda** [comment]
From what I understood, this can be closed since #846 solved the issue.

**Comment by craciunoiuc** [comment]
Yes, we can close this, thanks
