### ISSUE TITLE
`kraft run --rm` does not stop the application

### ISSUE THREAD

**Issue by StefanJum** [unikraft/kraftkit#632]
### Describe the bug

I'm running `sqlite` using kraftkit and passing the `--rm` option, but the application remains running in the backgroung:

```
sudo kraft run --rm --initrd initramfs.cpio

kraft ps
NAME           KERNEL                        ARGS        CREATED         STATUS   MEM  PLAT
jovial_frodo   project://sqlite:qemu-x86_64  chinook.db  2 seconds ago   running  0M   qemu/x86_64
```

**Comment by nderjung** [comment]
The instance is still running. When you stop it, it should be removed.

**Comment by StefanJum** [comment]
> The instance is still running. When you stop it, it should be removed.

Do you mean running `kraft stop`? If so, I did that, the application still shows in `kraft ps`, as exited, even if I ran it with `--rm`:

```
NAME           KERNEL                       ARGS        CREATED         STATUS  MEM  PLAT
youthful_koko  project://redis:qemu-x86_64  redis.conf  41 seconds ago  exited  0M   qemu/x86_64
```

**Comment by craciunoiuc** [comment]
The bug happens because the argument is not parsed correctly inside the cmdbuilder.

Theoretically, #545 will fix this, but we'll have to double-check

Edit: Apparently it was a race condition that didn't show up before
