### ISSUE TITLE
`-device pvpanic` doesn't work on AArch64

### ISSUE THREAD

**Issue by razvand** [unikraft/kraftkit#723]
### Describe the bug

When using KraftKit to run an AArch64 image, there is an error related to `-device pvpanic`. This appears to be an option only for x86_64. Sample run:

```console
$ kraft run -W .unikraft/build/helloworld_qemu-arm64
could not start and wait for QEMU process: qemu-system-aarch64: -device pvpanic: 'pvpanic' is not a valid device model name
exit status 1
```

### Steps to reproduce

Build [`app-helloworld`](https://github.com/unikraft/app-helloworld) and run using KraftKit:

```console
kraft run -W .unikraft/build/helloworld_qemu-arm64
```

### Expected behavior

There should be a normal run of the Unikraft instance, printing "Hello, world".

### Which architectures were you using or does this bug affect?

arm64

### Which operating system were you using or does this bug affect?

linux/debian

**Comment by nderjung** [comment]
This has been fixed in #720.
