### ISSUE TITLE
Add `kraft` wrapper script

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#73]
This issue tracks the addition of a bash script named `kraft` which can be installed alongside KraftKit which aliases the tools found within KraftKit.  The purpose of this script is to bridge the gap for those who have previously used [`kraft`](https://github.com/unikraft/kraft) and who are migrating to KraftKit.

Ultimately, the aliasing will invoke:

* `kraft build ...` -> `ukbuild ...`
* `kraft pkg ...` -> `ukpkg ...`
* `kraft run ...` -> `ukrung ...`

The script itself should be placed within `support/scripts/kraft`.

**Comment by craciunoiuc** [comment]
@nderjung this should be closed right? Or done the other way around `ukbuild ...` -> `kraft build ...`

**Comment by nderjung** [comment]
Yep! Closing :)
