### ISSUE TITLE
Migrate logging mechanisms to global contextualized logging

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#74]
Currently, KraftKit has littered through it via the option-based programming model `WithLogger`'s.  This is tedious and error-prone for users programming against KraftKit's APIs.

This issue tracks the use of a global log which, once imported, immediately enables the use of a configure logging system.  The approach should be similar to https://github.com/containerd/containerd/blob/main/log/context.go

All uses of `WithLogger` should subsequently be removed.

**Comment by craciunoiuc** [comment]
Done.
