### ISSUE TITLE
Handle dynamically embedding the initrd as part of a build

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#758]
### Feature request summary

This issue tracks the integration of embedding the CPIO archive as part of the unikernel following the introduction of https://github.com/unikraft/unikraft/pull/1070, KraftKit should handle this serialization dynamically by setting the appropriate KConfig option as well as part of the dynamic serialization of the file itself.

### Related architectures

None

### Related platforms

None

**Comment by craciunoiuc** [comment]
The PR in the core is about to be merged, we can start looking into this

**Comment by craciunoiuc** [comment]
Done.
