### ISSUE TITLE
The documentation is wrong on unikraft.org

### ISSUE THREAD

**Issue by Krutonium** [unikraft/kraftkit#760]
### Describe the bug

In the readme, there is a link to https://unikraft.org/docs/getting-started/ which includes a section on "Building an Application".

I'm assuming that it has drifted over time, because none of 

`kraft list update`
`kraft list`
`kraft up`

and so on actually work. For correct instructions, one must continue scrolling down the readme. Those instructions also don't include any mention of needing a  `Kraftfile`. 

### Which architectures were you using or does this bug affect?

x86_64, arm, arm64

### Which operating system were you using or does this bug affect?

linux/other

### Relevant log output

```shell
[nix-shell:~/.cache/nixpkgs-review/pr-252222/results/kraft/bin]$ kraft list update
unknown command "list" for "kraft"

[nix-shell:~/.cache/nixpkgs-review/pr-252222/results/kraft/bin]$ ./kraft up -p kvm -m x86_64 -t helloworld helloworld
unknown command "up" for "kraft"

Did you mean this?
        ps
        rm
        run
```

**Comment by nderjung** [comment]
Hi @Krutonium! Yes, we're in the process of rebuilding the unikraft.org website and will deploy a new version in the next two weeks with a revamped tutorial. For now, I suggest using the installation instructions that are part of the [`README.md`](https://github.com/unikraft/kraftkit/blob/staging/README.md)
