### ISSUE TITLE
Introduce environmental variable handling to `kraft build` and `kraft run`

### ISSUE THREAD

**Issue by nderjung** [unikraft/kraftkit#787]
### Feature request summary

This issue tracks allowing the parsing and passing of environmental variables from `kraft build` and `kraft run` via the command-line flag `-e` flag and an `env` element in the `Kraftfile` specification such that these key-values are correctly passed into [`posix-environ`](https://github.com/unikraft/unikraft/tree/staging/lib/posix-environ)

* **In the case of `kraft build`**, these can be statically set at compile-time such that these variables are persistent with the unikernel.

* **In the case of `kraft run`**, they are passed via [`uklibparam`](https://github.com/unikraft/unikraft/tree/staging/lib/uklibparam) via the syntax and requiring the KConfig option `CONFIG_LIBPOSIX_ENVIRON_LIBPARAM`:
   ```
   env.vars=[ "${NAME0}=${VALUE0}" "${NAME1}=${VALUE1}" ]
   ```

When no key is provided, for example `kraft run -e HOME`, the value should be automatically determined from the host environment via `os.Getenv`. 

A new wrapper library should be introduced in `unikraft/export/v0/posix-environ` to accommodate handling the list of key-value environmental variables and the correct format to be used when instantiating the VM.

To statically serialize environmental variables, a new top-level `env` element should be added to the `Kraftfile` specification such that these are passed in the same way to `kraft build` and `kraft run`.

Map form:
```yaml
spec: v0.6

env:
  KEY: value
```

List form:
```yaml
spec: v0.6

env:
- KEY=value
```

### Related architectures

None

### Related platforms

None

### Additional context

See [posix-environ: Handling Environmental Variables](https://unikraft.org/blog/2023-05-15-unikraft-releases-atlas#posix-environ-handling-environmental-variables-868) for additional details.

**Comment by LucaSeri** [comment]
Is anyone working on this at the moment? If not, can you please assign it to me?

**Comment by nderjung** [comment]
@LucaSeri 🪄

**Comment by nderjung** [comment]
@LucaSeri can you also introduce [`packmanager.PackWithEnv(env ...string)`](https://github.com/unikraft/kraftkit/blob/staging/packmanager/pack_options.go) and inject the environmental variables into the `ocispec.ImageConfig` object?

See:
- Somewhere around here https://github.com/unikraft/kraftkit/blob/staging/oci/pack.go#L239
- https://github.com/unikraft/kraftkit/blob/staging/oci/manifest.go#L210 (New method similar to this, `SetEnv(...string)`)
- https://github.com/opencontainers/image-spec/blob/v1.1.0/specs-go/v1/config.go#L32

Please & thank you! :)

**Comment by nderjung** [comment]
This draft PR may be interesting for you too see all the bits that need touching: https://github.com/unikraft/kraftkit/pull/1286
