### ISSUE TITLE
Web install script not working under Arch with package manager pacman

### ISSUE THREAD

**Issue by SorenEricMent** [unikraft/kraftkit#837]
### Describe the bug

Under Arch Linux, the script has multiple problems when the user choose to install with package manager
1. The script does not remove /tmp/kraftkit-bin/ after install but still expect it to be empty, which require one additional time of removing /tmp/kraftkit-bin/ if the user who want to reinstall didn't reboot after uninstall.
2. The script tried to build the package with `makepkg -si /tmp/kraftkit-bin`, however, even if /tmp/kraftkit-bin/PKGBUILD is presented the command will fall as makepkg is expecting to work under the current directory, the script should try to switch to /tmp/kraftkit-bin and execute `makepkg -si` directly

### Steps to reproduce

Use Arch Linux (technically, any distro that use pacman as the package manager as they all use makepkg for building packages)

execute the install command given at https://github.com/unikraft/kraftkit/
`curl --proto '=https' --tlsv1.2 -sSf https://get.kraftkit.sh | sh`

Choose the option to install with package manager

Error reproduced

### Expected behavior

Described above.

### Which architectures were you using or does this bug affect?

x86_64 but this bug should affect all architectures

### Which operating system were you using or does this bug affect?

Arch Linux
kernel: 6.5.4-1-cachyos-hardened

### Relevant log output

```shell
install kraftkit using package manager? [Y/n]: y
grep: warning: stray \ before n
installing kraftkit via package manager...
+ git clone https://aur.archlinux.org/kraftkit-bin.git /tmp/kraftkit-bin
Cloning into '/tmp/kraftkit-bin'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 20 (delta 5), reused 20 (delta 5), pack-reused 0
Receiving objects: 100% (20/20), 4.09 KiB | 4.09 MiB/s, done.
Resolving deltas: 100% (5/5), done.
+ makepkg -si /tmp/kraftkit-bin
==> ERROR: PKGBUILD does not exist.
command failed: makepkg -si /tmp/kraftkit-bin
```

**Comment by craciunoiuc** [comment]
Fixed in #838 not sure why this was not closed
