### ISSUE TITLE
`kraft rm` does not remove directories containing a `initramfs.cpio` file

### ISSUE THREAD

**Issue by antoineco** [unikraft/kraftkit#849]
### Describe the bug

After a failure to run a machine, `kraft rm` does not remove directories containing a `initramfs.cpio` file.

### Steps to reproduce

1. 
   ```console
   $ tree /var/kraftkit
   /var/kraftkit
   ├── machinev1alpha1
   └── oc
   ```
1.
   ```console
   $ kraft run --initrd ./fs0 -- /usr/sbin/nginx
   o.   .o       _ _               __ _
   Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
   oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
   oOo oOO| | | | |   (| | | (_) |  _) :_
    OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
                 Prometheus 0.14.0~9a17a93
   nginx: [emerg] fork() failed (38: Function not implemented)
   ^C
   ```
1. 
   ```console
   $ tree /var/kraftkit
   /var/kraftkit
   ├── d6671b22-9a64-4ce8-83a2-d4513f455c9e
   │   └── initramfs.cpio
   │   ├── machine.log
   │   ├── machine.pid
   │   ├── qemu.log
   │   ├── qemu_control.sock
   │   ├── qemu_events.sock
   │   └── qemu_mon.sock
   ├── machinev1alpha1
   └── oc
   ```
1.
   ```console
   $ kraft stop --all
   sharp_alfred
   ```
1.
   ```console
   $ tree /var/kraftkit
   /var/kraftkit
   ├── d6671b22-9a64-4ce8-83a2-d4513f455c9e
   │   └── initramfs.cpio
   │   ├── machine.log
   │   ├── qemu.log
   │   └── qemu.log
   ├── machinev1alpha1
   └── oc
   ```
1.
   ```console
   $ kraft rm --all
   sharp_alfred
   ```
1. 
   ```console
   $ tree /var/kraftkit
   /var/kraftkit
   ├── d6671b22-9a64-4ce8-83a2-d4513f455c9e
   │   └── initramfs.cpio
   ├── machinev1alpha1
   └── oc
   ```

### Expected behavior

KraftKit doesn't leak machine directories and cpio archives.

**Comment by antoineco** [comment]
The issue does not seem to happen consistently. I will add more details as soon as I can.

**Comment by craciunoiuc** [comment]
hmm, never happened to me, maybe something permission related

**Comment by antoineco** [comment]
No, I'm certain it's not permission related.

It _might_ be from running `rm --all` accidentally without prior `stop --all`, but most likely it's happening when the machine fails to start in the first place, and is therefore not registered in the internal store but nevertheless exists on disk.

I've been running quite a few machines with large initrd's lately, and occasionally ran out of memory during the extraction. However, the issue doesn't occur consistently. All I know right now is that my `/var/kraftkit` directory is regularly littered with `initramfs.cpio` files.

**Comment by craciunoiuc** [comment]
Ok, I have a vague idea why it happens and it is indeed as you thought. The machine is only registered after it was created successfully. But to be created correctly it needs to first start.

This means that if kraft fails somewhere between the creation/copy of the files, and the moment it fails, trace to these files is lost.

For example, you can spam `kraft run &` and get this error which will trigger the bug:
```
  E  could not open machine store: could not open machine store: Cannot acquire directory lock on "/home/cez/.local/share/kraftkit/runtime/machinev1alpha1".  Another process is using this Badger database. error: resource temporarily unavailable
```

**Comment by craciunoiuc** [comment]
If we can fetch the uuid and somehow detect that the error happened outside of unikraft, we can just delete the uuid folder

**Comment by craciunoiuc** [comment]
No longer an issue. The initrd is now stored in the build folder (`.unikraft/build/initramfs.cpio`), not the runtime folder. This should not be deleted on `kraft rm`
