### ISSUE TITLE
No output shown for helloworld on qemu/arm64

### ISSUE THREAD

**Issue by andreistan26** [unikraft/kraftkit#903]
### Describe the bug

When running with `kraft` on qemu/arm64 the following apps error with `platform kvm requested but it's not available`. 
Running on the same build with  `-W` option seems to hang the execution. 

The logs in `$HOME/.local/share/kraftkit/runtime/ID/machine.log` show the app starting correctly.

Related Issue: unikraft/app-helloworld#31

### Steps to reproduce

```
git clone https://github.com/unikraft/app-httpreply httpreply
cd httpreply/
kraft build --arch arm64 --plat qemu
kraft run --arch arm64 --plat qemu
```

### Expected behavior

The output of the unikernel running, not the error.

### Which architectures were you using or does this bug affect?

arm64

### Which operating system were you using or does this bug affect?

linux/debian

### Relevant log output

```shell
$cat machine.log

en1: Added
en1: Interface is up
Powered by
o.   .o       _ _               __ _
Oo   Oo  ___ (_) | __ __  __ _ ' _) :_
oO   oO ' _ `| | |/ /  _)' _` | |_|  _)
oOo oOO| | | | |   (| | | (_) |  _) :_
 OoOoO ._, ._:_:_,\_._,  .__,_:_, \___)
              Prometheus 0.14.0~75f0717
Listening on port 8123...
en1: Set IPv4 address 10.0.2.15 mask 255.255.255.0 gw 10.0.2.2
```

**Comment by LucaSeri** [comment]
Could you paste the output of the command `qemu-system-aarch64 --accel help`? The first part of the issue might be cause by the fact `kvm` is not supported in that binary.

As for the output not being shown, it seems that output is being properly generated with `qemu-x86_64` both without `-W` and with `-W`. I am only able to replicate the issue when running `arm64` with `-W`.

**Comment by andreistan26** [comment]
That is correct, `qemu/x86-64` works just fine. 

```console
$ qemu-system-aarch64 --accel help

Accelerators supported in QEMU binary:
tcg
```

**Comment by razvand** [comment]
@andreistan26 , @LucaSeri , I renamed the PR to make it more clear what this is about.

@craciunoiuc , this is a synchronization problem that we talked about. Is there a fix in sight for it?

**Comment by craciunoiuc** [comment]
We can add a flag to make it poll really fast, if it still doesn't work then we need to think of something else.

**Comment by craciunoiuc** [comment]
The error posted doesn't seem related to the race condition though

**Comment by LucaSeri** [comment]
From my digging, it seems that on `aarch64`, this line https://github.com/unikraft/kraftkit/blob/staging/cmd/kraft/run/run.go#L386 hangs and with no chan to track for updates on the log file, no output is being generated.

**Comment by craciunoiuc** [comment]
I will start looking into this. I can confirm I can also reproduce it for `arm64`

**Comment by craciunoiuc** [comment]
![image](https://github.com/unikraft/kraftkit/assets/46280801/8881ff24-910b-494e-810f-86f3a4e1f6c5)


Found the problem, it is because it the arm version does not contain the sgabios preamble
I will make sure it does not cut output in this case

**Comment by craciunoiuc** [comment]
```go
			if !qemuShowSgaBiosPreamble {
				if strings.Contains(line, "Booting from ") {
					qemuShowSgaBiosPreamble = true
				}
				continue
			}
```

When no `Booting from ROM` is found, it will skip all lines
