### ISSUE TITLE
OCI packages are displayed with the wrong index digest

### ISSUE THREAD

**Issue by antoineco** [unikraft/kraftkit#982]
### Describe the bug

KraftKit is displaying the wrong index digest.

Instead of displaying the digest of the OCI _manifest_, it is displaying the digest of the OCI _config_ (what Docker refers to as "image ID").

In the example below, we have an index which true digest (manifest hash) is `sha256:59886d5...`, but KraftKit is reporting `sha256:db738aa...` instead.

![image](https://github.com/unikraft/kraftkit/assets/3299086/0e0f1e13-ae50-41e8-a270-0d42a6c024d0)

```
TYPE  NAME                       VERSION  FORMAT  MANIFEST  INDEX    PLAT
app   index.unikraft.io/unik...  3.10     oci     7bda955   db738aa  fc/x86_64
app   index.unikraft.io/unik...  3.10     oci     30154a9   db738aa  qemu/x86_64
```

The problem here is that people won't be able to look up indexes using this digest inside their OCI registry.

### Steps to reproduce

`kraft pkg ls --apps`

### Expected behavior

```
TYPE  NAME                       VERSION  FORMAT  MANIFEST  INDEX    PLAT
app   index.unikraft.io/unik...  3.10     oci     7bda955   59886d5  fc/x86_64
app   index.unikraft.io/unik...  3.10     oci     30154a9   59886d5  qemu/x86_64
```

**Comment by nderjung** [comment]
Ok for me I cannot reproduce this bug, it shows me the index digest correctly. Could you please provide steps used before listing?

**Comment by antoineco** [comment]
All you need to do is compare the output of the catalog's GitHub Action with the digest shown in Harbor. They differ.
